<script setup lang="ts">
import {
  AlertCircle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Bell,
  Boxes,
  Captions,
  ChartColumn,
  Check,
  ChevronRight,
  ChevronsUpDown,
  Chrome,
  CircleDollarSign,
  Clapperboard,
  Cloud,
  Copy,
  Ellipsis,
  Eye,
  EyeOff,
  FileUp,
  FileText,
  Gift,
  Heart,
  Languages,
  LayoutDashboard,
  Lightbulb,
  Link,
  Loader2,
  LoaderCircle,
  LogOut,
  Menu,
  MessageSquare,
  MessageSquarePlus,
  MessageSquareText,
  MessageCircleMore,
  Monitor,
  Moon,
  PanelLeft,
  Plus,
  RefreshCcw,
  RefreshCw,
  Share,
  Sparkles,
  SquarePen,
  Sun,
  Text,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  UserRound,
  Users,
  Paperclip,
  Video,
  X,
} from "lucide-vue-next";
import { computed, markRaw } from "vue";

const iconMap = {
  AlertCircle: markRaw(AlertCircle),
  ArrowDown: markRaw(ArrowDown),
  ArrowRight: markRaw(ArrowRight),
  ArrowUp: markRaw(ArrowUp),
  Bell: markRaw(Bell),
  Boxes: markRaw(Boxes),
  Captions: markRaw(Captions),
  ChartColumn: markRaw(ChartColumn),
  Check: markRaw(Check),
  ChevronRight: markRaw(ChevronRight),
  ChevronsUpDown: markRaw(ChevronsUpDown),
  Chrome: markRaw(Chrome),
  CircleDollarSign: markRaw(CircleDollarSign),
  Clapperboard: markRaw(Clapperboard),
  Cloud: markRaw(Cloud),
  Copy: markRaw(Copy),
  Ellipsis: markRaw(Ellipsis),
  Eye: markRaw(Eye),
  EyeOff: markRaw(EyeOff),
  FileUp: markRaw(FileUp),
  FileText: markRaw(FileText),
  Gift: markRaw(Gift),
  Heart: markRaw(Heart),
  Languages: markRaw(Languages),
  LayoutDashboard: markRaw(LayoutDashboard),
  Lightbulb: markRaw(Lightbulb),
  Link: markRaw(Link),
  Loader2: markRaw(Loader2),
  LoaderCircle: markRaw(LoaderCircle),
  LogOut: markRaw(LogOut),
  Menu: markRaw(Menu),
  MessageSquare: markRaw(MessageSquare),
  MessageSquarePlus: markRaw(MessageSquarePlus),
  MessageSquareText: markRaw(MessageSquareText),
  MessageCircleMore: markRaw(MessageCircleMore),
  Monitor: markRaw(Monitor),
  Moon: markRaw(Moon),
  PanelLeft: markRaw(PanelLeft),
  Plus: markRaw(Plus),
  RefreshCcw: markRaw(RefreshCcw),
  RefreshCw: markRaw(RefreshCw),
  Share: markRaw(Share),
  Sparkles: markRaw(Sparkles),
  SquarePen: markRaw(SquarePen),
  Sun: markRaw(Sun),
  Text: markRaw(Text),
  ThumbsDown: markRaw(ThumbsDown),
  ThumbsUp: markRaw(ThumbsUp),
  Trash2: markRaw(Trash2),
  TrendingDown: markRaw(TrendingDown),
  TrendingUp: markRaw(TrendingUp),
  Upload: markRaw(Upload),
  UserRound: markRaw(UserRound),
  Users: markRaw(Users),
  Paperclip: markRaw(Paperclip),
  Video: markRaw(Video),
  X: markRaw(X),
} as const;

type IconName = keyof typeof iconMap;

const props = defineProps<{
  name: IconName;
}>();

const iconComponent = computed(() => iconMap[props.name]);
</script>

<template>
  <component :is="iconComponent" />
</template>
